/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatoriosIndexRouteImport } from './routes/relatorios.index'
import { Route as InspecaoIndexRouteImport } from './routes/inspecao.index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as InspecaoIdRouteImport } from './routes/inspecao.$id'
import { Route as ChecklistsIdRouteImport } from './routes/checklists.$id'
import { Route as BibliotecaHistoricoRouteImport } from './routes/biblioteca.historico'
import { Route as BibliotecaGlossarioRouteImport } from './routes/biblioteca.glossario'
import { Route as BibliotecaFavoritosRouteImport } from './routes/biblioteca.favoritos'
import { Route as BibliotecaDocumentosRouteImport } from './routes/biblioteca.documentos'
import { Route as BibliotecaAdminRouteImport } from './routes/biblioteca.admin'
import { Route as BibliotecaDocDocIdRouteImport } from './routes/biblioteca.doc.$docId'

const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosIndexRoute = RelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoIndexRoute = InspecaoIndexRouteImport.update({
  id: '/inspecao/',
  path: '/inspecao/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const InspecaoIdRoute = InspecaoIdRouteImport.update({
  id: '/inspecao/$id',
  path: '/inspecao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIdRoute = ChecklistsIdRouteImport.update({
  id: '/checklists/$id',
  path: '/checklists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaHistoricoRoute = BibliotecaHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaGlossarioRoute = BibliotecaGlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaFavoritosRoute = BibliotecaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaDocumentosRoute = BibliotecaDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaAdminRoute = BibliotecaAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BibliotecaRoute,
} as any)
const BibliotecaDocDocIdRoute = BibliotecaDocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => BibliotecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/biblioteca/documentos': typeof BibliotecaDocumentosRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/glossario': typeof BibliotecaGlossarioRoute
  '/biblioteca/historico': typeof BibliotecaHistoricoRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/inspecao/': typeof InspecaoIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/biblioteca/doc/$docId': typeof BibliotecaDocDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/biblioteca/documentos': typeof BibliotecaDocumentosRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/glossario': typeof BibliotecaGlossarioRoute
  '/biblioteca/historico': typeof BibliotecaHistoricoRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/inspecao': typeof InspecaoIndexRoute
  '/relatorios': typeof RelatoriosIndexRoute
  '/biblioteca/doc/$docId': typeof BibliotecaDocDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/biblioteca/admin': typeof BibliotecaAdminRoute
  '/biblioteca/documentos': typeof BibliotecaDocumentosRoute
  '/biblioteca/favoritos': typeof BibliotecaFavoritosRoute
  '/biblioteca/glossario': typeof BibliotecaGlossarioRoute
  '/biblioteca/historico': typeof BibliotecaHistoricoRoute
  '/checklists/$id': typeof ChecklistsIdRoute
  '/inspecao/$id': typeof InspecaoIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/inspecao/': typeof InspecaoIndexRoute
  '/relatorios/': typeof RelatoriosIndexRoute
  '/biblioteca/doc/$docId': typeof BibliotecaDocDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/biblioteca/admin'
    | '/biblioteca/documentos'
    | '/biblioteca/favoritos'
    | '/biblioteca/glossario'
    | '/biblioteca/historico'
    | '/checklists/$id'
    | '/inspecao/$id'
    | '/biblioteca/'
    | '/inspecao/'
    | '/relatorios/'
    | '/biblioteca/doc/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca/admin'
    | '/biblioteca/documentos'
    | '/biblioteca/favoritos'
    | '/biblioteca/glossario'
    | '/biblioteca/historico'
    | '/checklists/$id'
    | '/inspecao/$id'
    | '/biblioteca'
    | '/inspecao'
    | '/relatorios'
    | '/biblioteca/doc/$docId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/biblioteca/admin'
    | '/biblioteca/documentos'
    | '/biblioteca/favoritos'
    | '/biblioteca/glossario'
    | '/biblioteca/historico'
    | '/checklists/$id'
    | '/inspecao/$id'
    | '/biblioteca/'
    | '/inspecao/'
    | '/relatorios/'
    | '/biblioteca/doc/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ChecklistsIdRoute: typeof ChecklistsIdRoute
  InspecaoIdRoute: typeof InspecaoIdRoute
  InspecaoIndexRoute: typeof InspecaoIndexRoute
  RelatoriosIndexRoute: typeof RelatoriosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/': {
      id: '/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof RelatoriosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao/': {
      id: '/inspecao/'
      path: '/inspecao'
      fullPath: '/inspecao/'
      preLoaderRoute: typeof InspecaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/inspecao/$id': {
      id: '/inspecao/$id'
      path: '/inspecao/$id'
      fullPath: '/inspecao/$id'
      preLoaderRoute: typeof InspecaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$id': {
      id: '/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof ChecklistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/historico': {
      id: '/biblioteca/historico'
      path: '/historico'
      fullPath: '/biblioteca/historico'
      preLoaderRoute: typeof BibliotecaHistoricoRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/glossario': {
      id: '/biblioteca/glossario'
      path: '/glossario'
      fullPath: '/biblioteca/glossario'
      preLoaderRoute: typeof BibliotecaGlossarioRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/favoritos': {
      id: '/biblioteca/favoritos'
      path: '/favoritos'
      fullPath: '/biblioteca/favoritos'
      preLoaderRoute: typeof BibliotecaFavoritosRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/documentos': {
      id: '/biblioteca/documentos'
      path: '/documentos'
      fullPath: '/biblioteca/documentos'
      preLoaderRoute: typeof BibliotecaDocumentosRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/admin': {
      id: '/biblioteca/admin'
      path: '/admin'
      fullPath: '/biblioteca/admin'
      preLoaderRoute: typeof BibliotecaAdminRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/biblioteca/doc/$docId': {
      id: '/biblioteca/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/biblioteca/doc/$docId'
      preLoaderRoute: typeof BibliotecaDocDocIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaAdminRoute: typeof BibliotecaAdminRoute
  BibliotecaDocumentosRoute: typeof BibliotecaDocumentosRoute
  BibliotecaFavoritosRoute: typeof BibliotecaFavoritosRoute
  BibliotecaGlossarioRoute: typeof BibliotecaGlossarioRoute
  BibliotecaHistoricoRoute: typeof BibliotecaHistoricoRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  BibliotecaDocDocIdRoute: typeof BibliotecaDocDocIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaAdminRoute: BibliotecaAdminRoute,
  BibliotecaDocumentosRoute: BibliotecaDocumentosRoute,
  BibliotecaFavoritosRoute: BibliotecaFavoritosRoute,
  BibliotecaGlossarioRoute: BibliotecaGlossarioRoute,
  BibliotecaHistoricoRoute: BibliotecaHistoricoRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  BibliotecaDocDocIdRoute: BibliotecaDocDocIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ChecklistsIdRoute: ChecklistsIdRoute,
  InspecaoIdRoute: InspecaoIdRoute,
  InspecaoIndexRoute: InspecaoIndexRoute,
  RelatoriosIndexRoute: RelatoriosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
